#!/bin/sh

#Substitute enivronment variables into files
sed -i "s/{{MM_YSF_SERVER}}/$MM_YSF_SERVER/" /opt/MMDVM_Bridge.ini
sed -i "s/{{MM_YSF_PORT}}/$MM_YSF_PORT/" /opt/MMDVM_Bridge.ini
sed -i "s/{{MM_DMR_SERVER}}/$MM_DMR_SERVER/" /opt/MMDVM_Bridge.ini
sed -i "s/{{MM_CALL}}/$MM_CALL/" /opt/MMDVM_Bridge.ini
sed -i "s/{{MM_ID}}/$MM_ID/" /opt/MMDVM_Bridge.ini
sed -i "s/{{MM_DMR_PORT}}/$MM_DMR_PORT/" /opt/MMDVM_Bridge.ini
sed -i "s/{{MM_OPTIONS}}/$MM_OPTIONS/" /opt/MMDVM_Bridge.ini
sed -i "s/{{MM_LOCATION}}/$MM_LOCATION/" /opt/MMDVM_Bridge.ini
sed -i "s/{{MM_TG}}/$MM_TG/g" /opt/DVSwitch.ini

#Run processes
export DVSWITCH=/opt/DVSwitch.ini
cd /opt/
#arch=`/usr/bin/uname -m`
./DMRIDUpdate.sh
/opt/MMDVM_Bridge/bin/MMDVM_Bridge.amd64 ./MMDVM_Bridge.ini